### ISSUE TITLE
When dot files are included, dot-prefixed directories are included

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [ksmolyanin/run-for-every-file#1]
```
> run-for-every-file --dot --src "node_modules/shenanigans-manager/setup/default/" --file "**/*" --run "mustache package.json {{src-file}} {{file}}" --dest "."

COMMAND: mustache package.json node_modules/shenanigans-manager/setup/default/.gitignore .gitignore
COMMAND: mustache package.json node_modules/shenanigans-manager/setup/default/.npmignore .npmignore
COMMAND: mustache package.json node_modules/shenanigans-manager/setup/default/.travis.yml .travis.yml
COMMAND: mustache package.json node_modules/shenanigans-manager/setup/default/.vscode/ .vscode/
Error while reading file: EISDIR: illegal operation on a directory, read
child_process.js:614
    throw err;
    ^

Error: Command failed: mustache package.json node_modules/shenanigans-manager/setup/default/.vscode/ .vscode/
Error while reading file: EISDIR: illegal operation on a directory, read

    at checkExecSyncError (child_process.js:574:11)
    at execSync (child_process.js:611:13)
    at run (C:\Code\Shenanigans\fullscreenpokemon\node_modules\run-for-every-file\run-for-every-file.js:118:24)
    at srcFiles.forEach (C:\Code\Shenanigans\fullscreenpokemon\node_modules\run-for-every-file\run-for-every-file.js:157:5)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Code\Shenanigans\fullscreenpokemon\node_modules\run-for-every-file\run-for-every-file.js:155:10)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
```

I think the root problem is that glob is sending back directory names like `.vscode` when it shouldn't. I skimmed the glob docs & issues and didn't see anything mentioning this behavior. One solution could be to always check `fs.lstatSync(filePath).isFile()` if `includeDotFIles` is true.

**Comment by ksmolyanin** [comment]
Hi! Thank you for your efforts! The solution you've found is great! But I can't merge you pull request in its current state. I think we shouldn't change the meaning of any existing command line flags because some other people who use this utility become a bit unhappy if this `--dot` flag change its behavior. So I'd suggest to leave `--dot` for both dirs and files and add `--dotFiles` flag for the behavior you desire.

**Comment by JoshuaKGoldberg** [comment]
Sounds good! +1 for compat.

**Comment by JoshuaKGoldberg** [comment]
(sent a new PR because it's so different from the other one, and having `patch-1` as the branch name was irritating me 😄)
